# Setup IRL-Based Data Room - Workflow Configuration
name: "setup-irl-data-room"
description: "Intelligent data room setup based on Information Request List (IRL) or standard M&A checklist"
author: "M&A Deal Intelligence Platform"

# Configuration
config_source: "{module-root}/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module paths
installed_path: "{module-root}/workflows/setup-irl-data-room"

# Variables
deal_name: "{{user_input}}"
data_room_path: "{config_source}:data_room_path"
irl_storage_path: "{{data_room_path}}/irl"
retrofit_mode: "{{user_input:false}}"  # Set to true when adding IRL to existing docs

# This is an action workflow (no template output)
template: false
instructions: "{installed_path}/instructions.md"

standalone: true

# Metadata
version: "1.0.0"
category: "setup"
tags: ["setup", "irl", "data-room", "checklist"]
